// EIS Funding Readiness Assessment — 110 Checklist Items (Seed Data)
// Track: 'grant' or 'proposal' (singular, matching AssessmentItem entity)
// na_structures: structures where the item does NOT apply
// applies_to: if populated, item ONLY applies to these structures

module.exports = [
  // ===== GRANT TRACK — Level 1: Foundational Readiness (15 items, 4 gate) =====
  { track: 'grant', level: 1, item_index: 1, sort_order: 101, text: 'Organization is legally registered with the state', points: 2, is_gate: true, level_name: 'Foundational Readiness', na_structures: ['fiscal', 'gov'] },
  { track: 'grant', level: 1, item_index: 2, sort_order: 102, text: 'EIN obtained from the IRS', points: 2, is_gate: true, level_name: 'Foundational Readiness', na_structures: ['fiscal'] },
  { track: 'grant', level: 1, item_index: 3, sort_order: 103, text: 'Legal structure clearly identified (nonprofit, for-profit, fiscally sponsored, sole proprietor)', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 4, sort_order: 104, text: 'Dedicated business or organizational bank account established', points: 2, is_gate: true, level_name: 'Foundational Readiness', na_structures: ['fiscal', 'gov'] },
  { track: 'grant', level: 1, item_index: 5, sort_order: 105, text: 'Clear, written mission statement', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 6, sort_order: 106, text: 'Defined population or community served', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 7, sort_order: 107, text: 'Specific services or programs identified', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 8, sort_order: 108, text: 'Documented evidence of community need or demand', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 9, sort_order: 109, text: 'Startup or annual operating budget drafted', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 10, sort_order: 110, text: 'Planned use of grant funds outlined', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 11, sort_order: 111, text: 'Target funding amount identified', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 12, sort_order: 112, text: 'Organizational leadership roles defined', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 13, sort_order: 113, text: 'Formation documents accessible (articles, bylaws, operating agreement)', points: 1, is_gate: false, level_name: 'Foundational Readiness', na_structures: ['sole', 'fiscal', 'gov'] },
  { track: 'grant', level: 1, item_index: 14, sort_order: 114, text: 'Basic bookkeeping or accounting system in place', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'grant', level: 1, item_index: 15, sort_order: 115, text: 'Staff or contractor time can be dedicated to grant preparation', points: 1, is_gate: false, level_name: 'Foundational Readiness' },

  // ===== GRANT TRACK — Level 2: Fundability Readiness (20 items, 2 gate) =====
  { track: 'grant', level: 2, item_index: 1, sort_order: 201, text: 'Decision-making authority clearly established', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 2, sort_order: 202, text: 'Board is active and meeting regularly (if nonprofit)', points: 1, is_gate: false, level_name: 'Fundability Readiness', applies_to: ['501c3', 'othernp', 'church'] },
  { track: 'grant', level: 2, item_index: 3, sort_order: 203, text: 'Board understands its fiduciary responsibility (if nonprofit)', points: 1, is_gate: false, level_name: 'Fundability Readiness', applies_to: ['501c3', 'othernp', 'church'] },
  { track: 'grant', level: 2, item_index: 4, sort_order: 204, text: 'Data-supported problem statement developed', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 5, sort_order: 205, text: 'Program activities clearly defined', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 6, sort_order: 206, text: 'Activities logically connected to intended outcomes', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 7, sort_order: 207, text: 'Outputs and outcomes defined and measurable', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 8, sort_order: 208, text: 'Realistic implementation timeline identified', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 9, sort_order: 209, text: 'Performance metrics identified', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 10, sort_order: 210, text: 'Data collection method identified', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 11, sort_order: 211, text: 'Responsibility for evaluation formally assigned', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 12, sort_order: 212, text: 'Financial controls and approval thresholds in place', points: 2, is_gate: true, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 13, sort_order: 213, text: 'Able to track and report grant funds separately (fund accounting)', points: 2, is_gate: true, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 14, sort_order: 214, text: 'Prior experience managing restricted or designated funds', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 15, sort_order: 215, text: 'Written financial policies and procedures', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 16, sort_order: 216, text: 'Cash flow sufficient to operate reimbursement-based grants', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 17, sort_order: 217, text: 'Program budget can be built at the line-item level', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 18, sort_order: 218, text: 'Strategic partners identified', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 19, sort_order: 219, text: 'Partner roles and contributions defined', points: 1, is_gate: false, level_name: 'Fundability Readiness' },
  { track: 'grant', level: 2, item_index: 20, sort_order: 220, text: 'Willing to formalize partnerships through an MOU or letter of agreement', points: 1, is_gate: false, level_name: 'Fundability Readiness' },

  // ===== GRANT TRACK — Level 3: Competitive Readiness (20 items, 2 gate) =====
  { track: 'grant', level: 3, item_index: 1, sort_order: 301, text: 'Organization in good standing with the state and the IRS', points: 2, is_gate: true, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 2, sort_order: 302, text: 'Required registrations complete (SAM.gov / UEI if pursuing federal funding)', points: 2, is_gate: true, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 3, sort_order: 303, text: 'No unresolved audit or compliance findings', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 4, sort_order: 304, text: 'Aware of the Single Audit threshold and its requirements', points: 1, is_gate: false, level_name: 'Competitive Readiness', na_structures: ['sole', 'llc', 'corp', 'notformed', 'notsure'] },
  { track: 'grant', level: 3, item_index: 5, sort_order: 305, text: 'Indirect cost rate established, or de minimis / NICRA status understood', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 6, sort_order: 306, text: 'Required insurance coverage in place or obtainable', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 7, sort_order: 307, text: 'Named internal grants lead identified', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 8, sort_order: 308, text: 'Post-award reporting responsibility assigned to a specific role', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 9, sort_order: 309, text: 'Ability to track time and effort for grant-funded personnel', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 10, sort_order: 310, text: 'Grant tracking system or submission calendar in place', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 11, sort_order: 311, text: 'Active grant pipeline maintained', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 12, sort_order: 312, text: 'Prior grant or contract award experience', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 13, sort_order: 313, text: 'Able to research and articulate funder priorities', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 14, sort_order: 314, text: 'Able to assess alignment and decline misaligned opportunities', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 15, sort_order: 315, text: 'Internal review and approval process supports on-time submission', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 16, sort_order: 316, text: 'Data system can produce funder-required reports', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 17, sort_order: 317, text: 'Matching or cost-share capacity assessed', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 18, sort_order: 318, text: 'Sustainability beyond the grant period addressed', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 19, sort_order: 319, text: 'Willing to incorporate reviewer feedback and resubmit', points: 1, is_gate: false, level_name: 'Competitive Readiness' },
  { track: 'grant', level: 3, item_index: 20, sort_order: 320, text: 'Lessons learned from prior submissions documented', points: 1, is_gate: false, level_name: 'Competitive Readiness' },

  // ===== PROPOSAL TRACK — Level 1: Foundational Readiness (15 items, 4 gate) =====
  { track: 'proposal', level: 1, item_index: 1, sort_order: 1101, text: 'Business legally registered and in good standing with the state', points: 2, is_gate: true, level_name: 'Foundational Readiness', na_structures: ['fiscal', 'gov'] },
  { track: 'proposal', level: 1, item_index: 2, sort_order: 1102, text: 'EIN obtained from the IRS', points: 2, is_gate: true, level_name: 'Foundational Readiness', na_structures: ['fiscal'] },
  { track: 'proposal', level: 1, item_index: 3, sort_order: 1103, text: 'Current W-9 prepared and available on request', points: 1, is_gate: false, level_name: 'Foundational Readiness', na_structures: ['fiscal', 'gov'] },
  { track: 'proposal', level: 1, item_index: 4, sort_order: 1104, text: 'Dedicated business bank account established', points: 2, is_gate: true, level_name: 'Foundational Readiness', na_structures: ['fiscal', 'gov'] },
  { track: 'proposal', level: 1, item_index: 5, sort_order: 1105, text: 'Required business licenses and permits current', points: 1, is_gate: false, level_name: 'Foundational Readiness', na_structures: ['gov'] },
  { track: 'proposal', level: 1, item_index: 6, sort_order: 1106, text: 'UEI obtained and SAM.gov registration active (if pursuing government contracts)', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'proposal', level: 1, item_index: 7, sort_order: 1107, text: 'Registered in relevant state, county, and city vendor portals', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'proposal', level: 1, item_index: 8, sort_order: 1108, text: 'Required insurance in place (general liability, professional liability, workers\' comp as applicable)', points: 2, is_gate: true, level_name: 'Foundational Readiness' },
  { track: 'proposal', level: 1, item_index: 9, sort_order: 1109, text: 'Certificate of insurance can be produced within 48 hours', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'proposal', level: 1, item_index: 10, sort_order: 1110, text: 'Diversity certifications obtained or in process (MBE / WBE / EDGE / DBE / 8(a) / HUBZone)', points: 1, is_gate: false, level_name: 'Foundational Readiness', na_structures: ['501c3', 'othernp', 'church', 'gov', 'fiscal'] },
  { track: 'proposal', level: 1, item_index: 11, sort_order: 1111, text: 'Current-year and prior-year financial statements available', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'proposal', level: 1, item_index: 12, sort_order: 1112, text: 'One-page capability statement developed and current', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'proposal', level: 1, item_index: 13, sort_order: 1113, text: 'Standard company overview and boilerplate maintained', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'proposal', level: 1, item_index: 14, sort_order: 1114, text: 'Key personnel resumes current and consistently formatted', points: 1, is_gate: false, level_name: 'Foundational Readiness' },
  { track: 'proposal', level: 1, item_index: 15, sort_order: 1115, text: 'Three verifiable client references available', points: 1, is_gate: false, level_name: 'Foundational Readiness' },

  // ===== PROPOSAL TRACK — Level 2: Bid Readiness (20 items, 0 gate) =====
  { track: 'proposal', level: 2, item_index: 1, sort_order: 1201, text: 'Written bid / no-bid decision criteria', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 2, sort_order: 1202, text: 'Named person responsible for monitoring solicitation postings', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 3, sort_order: 1203, text: 'Actively monitoring relevant bid sources (state procurement, SAM.gov, local government, nonprofit RFPs)', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 4, sort_order: 1204, text: 'Past performance documented with measurable outcomes', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 5, sort_order: 1205, text: 'Case studies or project summaries written and ready to adapt', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 6, sort_order: 1206, text: 'Loaded labor rate structure established for each role', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 7, sort_order: 1207, text: 'Indirect or overhead rate calculated and defensible', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 8, sort_order: 1208, text: 'Pricing can accommodate fixed-price, time-and-materials, and cost-reimbursable structures', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 9, sort_order: 1209, text: 'Standard staffing plan template with role descriptions and level of effort', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 10, sort_order: 1210, text: 'Bench of qualified subcontractors or 1099 contractors identified', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 11, sort_order: 1211, text: 'Teaming and subcontractor agreements templated', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 12, sort_order: 1212, text: 'Able to translate a scope of work into a work plan with milestones', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 13, sort_order: 1213, text: 'Able to build and defend a deliverable schedule', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 14, sort_order: 1214, text: 'Proposal template library maintained (technical approach, management approach, past performance)', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 15, sort_order: 1215, text: 'Able to meet formatting, font, margin, and page-limit requirements', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 16, sort_order: 1216, text: 'Someone assigned to compliance-check the response against the RFP checklist before submission', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 17, sort_order: 1217, text: 'Capacity assessment completed before committing to a bid', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 18, sort_order: 1218, text: 'Sufficient lead time built in rather than starting near the deadline', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 19, sort_order: 1219, text: 'Question-and-answer deadlines tracked and questions submitted when needed', points: 1, is_gate: false, level_name: 'Bid Readiness' },
  { track: 'proposal', level: 2, item_index: 20, sort_order: 1220, text: 'Required forms and certifications can be completed accurately (non-collusion, debarment, affirmative action)', points: 1, is_gate: false, level_name: 'Bid Readiness' },

  // ===== PROPOSAL TRACK — Level 3: Performance Readiness (20 items, 2 gate) =====
  { track: 'proposal', level: 3, item_index: 1, sort_order: 1301, text: 'Contract management system or tracking process in place', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 2, sort_order: 1302, text: 'Able to invoice on the schedule and in the format the contract requires', points: 2, is_gate: true, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 3, sort_order: 1303, text: 'Cash flow sufficient to carry net-30 to net-60 payment terms', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 4, sort_order: 1304, text: 'Time tracking system in place for billable staff and contractors', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 5, sort_order: 1305, text: 'Cost allocation methodology documented and defensible in an audit', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 6, sort_order: 1306, text: 'Able to segregate and report costs by contract', points: 2, is_gate: true, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 7, sort_order: 1307, text: 'Understand the procurement rules that apply (FAR, 2 CFR 200, state or local code)', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 8, sort_order: 1308, text: 'Bonding capacity assessed if the work requires it', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 9, sort_order: 1309, text: 'Written quality control or quality assurance plan', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 10, sort_order: 1310, text: 'Project management methodology defined', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 11, sort_order: 1311, text: 'Named contract or project manager identified for each engagement', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 12, sort_order: 1312, text: 'Able to meet the required reporting cadence and deliverable schedule', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 13, sort_order: 1313, text: 'Able to meet prevailing wage or labor standards where applicable', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 14, sort_order: 1314, text: 'Data security and confidentiality practices documented', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 15, sort_order: 1315, text: 'Conflict of interest policy in place', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 16, sort_order: 1316, text: 'Able to process a scope change or contract modification formally', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 17, sort_order: 1317, text: 'Records retention practices meet contract requirements', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 18, sort_order: 1318, text: 'Debriefs requested and documented after a loss', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 19, sort_order: 1319, text: 'Win / loss outcomes tracked over time', points: 1, is_gate: false, level_name: 'Performance Readiness' },
  { track: 'proposal', level: 3, item_index: 20, sort_order: 1320, text: 'Renewal and recompete dates tracked on a calendar', points: 1, is_gate: false, level_name: 'Performance Readiness' },
];