// Role-based permission system

export const ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  COACH: 'coach',
  USER: 'user',
  GUEST: 'guest'
};

export const PERMISSIONS = {
  VIEW_DOCUMENTS: 'view_documents',
  CREATE_DOCUMENTS: 'create_documents',
  EDIT_DOCUMENTS: 'edit_documents',
  DELETE_DOCUMENTS: 'delete_documents',
  VIEW_TEMPLATES: 'view_templates',
  CREATE_TEMPLATES: 'create_templates',
  EDIT_TEMPLATES: 'edit_templates',
  DELETE_TEMPLATES: 'delete_templates',
  VIEW_LEARNING: 'view_learning',
  CREATE_LEARNING: 'create_learning',
  EDIT_LEARNING: 'edit_learning',
  DELETE_LEARNING: 'delete_learning',
  ACCESS_ADMIN_PORTAL: 'access_admin_portal',
  MANAGE_USERS: 'manage_users',
  MANAGE_ORGANIZATIONS: 'manage_organizations',
  MANAGE_SETTINGS: 'manage_settings',
  VIEW_EVENTS: 'view_events',
  CREATE_EVENTS: 'create_events',
  EDIT_EVENTS: 'edit_events',
  DELETE_EVENTS: 'delete_events',
  VIEW_DISCUSSIONS: 'view_discussions',
  CREATE_DISCUSSIONS: 'create_discussions',
  EDIT_DISCUSSIONS: 'edit_discussions',
  DELETE_DISCUSSIONS: 'delete_discussions',
  VIEW_PROJECTS: 'view_projects',
  CREATE_PROJECTS: 'create_projects',
  EDIT_PROJECTS: 'edit_projects',
  DELETE_PROJECTS: 'delete_projects',
};

const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DOCUMENTS, PERMISSIONS.CREATE_DOCUMENTS, PERMISSIONS.EDIT_DOCUMENTS, PERMISSIONS.DELETE_DOCUMENTS,
    PERMISSIONS.VIEW_TEMPLATES, PERMISSIONS.CREATE_TEMPLATES, PERMISSIONS.EDIT_TEMPLATES, PERMISSIONS.DELETE_TEMPLATES,
    PERMISSIONS.VIEW_LEARNING, PERMISSIONS.CREATE_LEARNING, PERMISSIONS.EDIT_LEARNING, PERMISSIONS.DELETE_LEARNING,
    PERMISSIONS.ACCESS_ADMIN_PORTAL, PERMISSIONS.MANAGE_USERS, PERMISSIONS.MANAGE_ORGANIZATIONS, PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_EVENTS, PERMISSIONS.CREATE_EVENTS, PERMISSIONS.EDIT_EVENTS, PERMISSIONS.DELETE_EVENTS,
    PERMISSIONS.VIEW_DISCUSSIONS, PERMISSIONS.CREATE_DISCUSSIONS, PERMISSIONS.EDIT_DISCUSSIONS, PERMISSIONS.DELETE_DISCUSSIONS,
    PERMISSIONS.VIEW_PROJECTS, PERMISSIONS.CREATE_PROJECTS, PERMISSIONS.EDIT_PROJECTS, PERMISSIONS.DELETE_PROJECTS,
  ],
  [ROLES.COACH]: [
    PERMISSIONS.VIEW_DOCUMENTS, PERMISSIONS.CREATE_DOCUMENTS, PERMISSIONS.EDIT_DOCUMENTS,
    PERMISSIONS.VIEW_TEMPLATES, PERMISSIONS.VIEW_LEARNING, PERMISSIONS.CREATE_LEARNING, PERMISSIONS.EDIT_LEARNING,
    PERMISSIONS.VIEW_EVENTS, PERMISSIONS.CREATE_EVENTS, PERMISSIONS.VIEW_DISCUSSIONS, PERMISSIONS.CREATE_DISCUSSIONS,
    PERMISSIONS.VIEW_PROJECTS, PERMISSIONS.CREATE_PROJECTS, PERMISSIONS.EDIT_PROJECTS,
  ],
  [ROLES.USER]: [
    PERMISSIONS.VIEW_DOCUMENTS, PERMISSIONS.CREATE_DOCUMENTS, PERMISSIONS.EDIT_DOCUMENTS,
    PERMISSIONS.VIEW_TEMPLATES, PERMISSIONS.VIEW_LEARNING, PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_DISCUSSIONS, PERMISSIONS.CREATE_DISCUSSIONS, PERMISSIONS.VIEW_PROJECTS, PERMISSIONS.CREATE_PROJECTS,
  ],
  [ROLES.GUEST]: [
    PERMISSIONS.VIEW_LEARNING, PERMISSIONS.VIEW_EVENTS, PERMISSIONS.VIEW_DISCUSSIONS,
  ],
};

export function hasPermission(userRole, permission) {
  if (!userRole) return false;
  const permissions = ROLE_PERMISSIONS[userRole] || [];
  return permissions.includes(permission);
}

export function hasAnyPermission(userRole, permissionList) {
  return permissionList.some(permission => hasPermission(userRole, permission));
}

export function hasAllPermissions(userRole, permissionList) {
  return permissionList.every(permission => hasPermission(userRole, permission));
}

export function canAccessAdminPortal(userRole) {
  return hasPermission(userRole, PERMISSIONS.ACCESS_ADMIN_PORTAL);
}